name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
      name: Lint JavaScript Files
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run Linter
        run: |
          # Added --options to support modern ES6+ features
          find ./giftlink-backend -name app.js -exec jshint --esversion:11 {} +
          find ./giftlink-backend -name auth.js -exec jshint --esversion:11 {} +
          find ./giftlink-backend -name giftRoutes.js -exec jshint --esversion:11 {} +
          find ./giftlink-backend -name searchRoutes.js -exec jshint --esversion:11 {} +
          echo "Linted all the js files successfully"

  client_build:
      name: Build client
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Run build
        run: |
          cd giftlink-frontend
          npm install
          npm run build
          echo "Client-side build successfully"
